name: Publish Docker Image

on:
  push:
    branches:
      - master

env:
  DOCKER_IMAGE_VERSION: 2.0.17.2

jobs:
  publish_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: actindi-dev
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: |
          docker build --tag ghcr.io/actindi-dev/proxysql-with-tools2:latest \
          --tag ghcr.io/actindi-dev/proxysql-with-tools2:${{ env.DOCKER_IMAGE_VERSION }} \
          .
      - name: Push Docker Image
        run: |
          docker push ghcr.io/actindi-dev/proxysql-with-tools2:latest
          docker push ghcr.io/actindi-dev/proxysql-with-tools2:${{ env.DOCKER_IMAGE_VERSION }}
